---
driver:
  name: vagrant

provisioner:
  name: salt_solo
  log_level: debug
  require_chef: false
  formula: docker
  state_top:
    base:
      '*':
        - docker

platforms:
  - name: bento/debian-8.9

suites:
  - name: version-17.09
    provisioner:
      pillars:
        top.sls:
          base:
            '*':
              - docker
        docker.sls:
          docker:
            lookup:
              version: 17.06.2~ce-0~debian
              repo_name: http://mirror-ka.i.fhe3.net/docker/debian/
              repo_keyurl: http://mirror-ka.i.fhe3.net/docker/debian/gpg
              repo_component: stable

verifier:
  name: shell
  remote_exec: false
  command: testinfra -vvv --connection=docker --hosts=root@$KITCHEN_CONTAINER_ID --junit-xml junit-$KITCHEN_INSTANCE.xml test/integration/$KITCHEN_SUITE
